apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xwt5vckb6-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xwt5vckb6-java-springboot-gitops